apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-nome-deployment
  namespace: nome-namespace
spec:
  minReplicas: minimoReplicas
  maxReplicas: maximoReplicas
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nome-deployment
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 480Mi

